# config.yml
#
# DylanTodd
# 10.12.19

title: Dylan Todd
subtitle: Jelm, WY
logo: "/images/profilephoto.jpg?raw=true" # profile photo 
# eventual logo here for affiliated companies
description:
  Projects 
  <br>mechChain<br>
  <br>cancerLancer<br>
  Contact Information
  <br>307.421.0383<br>
  <br>dylan.todd777@gmail.com<br>
  <a href="https://www.linkedin.com/in/dylan-todd/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-149905245-1 # Google Analytics tracking ID
