# config.yml
#
# DylanTodd
# 10.12.19
# Updated 11.05.19

title: Dylan Todd
subtitle: Jelm, WY
logo: "/images/profilephoto.jpg?raw=true" # profile photo 
# eventual logo here for affiliated companies
  # lighthouse collective
  # contrarian productions
  # sage technologies
description:
  Personal website to provide a brief overview of who I am and an explanation of some of my work on gitHub.
#  Projects 
#  <br>mechChain<br>
#  <br>cancerLancer<br>
#  Contact Information
#  <br>307.421.0383<br>
#  <br>dylan.todd777@gmail.com<br>
  <a href="https://www.linkedin.com/in/dylan-todd/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-149905245-1 # Google Analytics tracking ID
